apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cert-issuer-key
    solvers:
    - http01:
        ingress:
          class: haproxy
          serviceType: ClusterIP