apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: "default"
spec:
  selector:
    matchLabels:
      app: proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - image: "jcmoraisjr/haproxy-ingress:v0.14.8"
          name: proxy-service
          imagePullPolicy: "Always"
          args: 
            - --reload-strategy=native
            - --configmap=default/proxy-conf
          env:
            - name: POD_NAME
              value: proxy
            - name: POD_NAMESPACE
              value: default
          ports:
            - containerPort: 80
              name: http-port
            - containerPort: 443
              name: https-port

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: "default"
spec:
  type: ClusterIP
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https-port
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-conf
  namespace: default
data:
  dynamic-scaling: "true"
  backend-server-slots-increment: "4"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-service-crb 
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: default