apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verizon-sample-app-ingress
  namespace: "default"
  annotations:
    cert-manager.io/issuer: letsencrypt-cert-issuer
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: haproxy
    haproxy-ingress.github.io/timeout-server: "3600s"
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - "<hostname>"
      secretName: verizon-syntasa-certs
  rules:
    - host: "<hostname>"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: sample-app-service
                port:
                  number: 5678
